
// get all users
GET http://localhost:3001/users



###
// get one user
GET http://localhost:3001/users/6340dfd9e3d78e39086bee9b



###
// Register user
POST http://localhost:3001/register
Content-Type: application/json

{ 
    "name": "Norton",
    "password": "password"
}



###
// login user 
POST http://localhost:3001/login
Content-Type: application/json

{ 
    "name": "Betty",
    "password": "password"
}



###
// user profile
GET http://localhost:3001/profile



###
// logout user
GET http://localhost:3001/logout


###
// update user
PATCH http://localhost:3001/users/6340eeecaa7c19c62560eaa5
Content-Type: application/json

{ 
    "name": "Jacob",
    "password": "password123"
}



###
// delete user
DELETE  http://localhost:3001/users/634230a32f8326f578945f41