GET http://localhost:3001/DiscGophers

###


GET http://localhost:3001/DiscGophers/633df4a5704d9210286b281a


###
// creating a new disc
POST http://localhost:3001/DiscGophers/633df4a5704d9210286b281a/disc
Content-Type: application/json

{
    "name": "Eagle"
}



###
//DELETING A DISC
DELETE http://localhost:3001/DiscGophers/disc/633f6e473707c88d48f951de


### 
// GETTING ONE DISC

GET  http://localhost:3001/DiscGophers/disc/633f54e51c24e10c499a50b7



###
// get all discs

GET http://localhost:3001/DiscGophers/disc


###


//getting one disc
GET http://localhost:3001/DiscGophers/disc/633f6e473707c88d48f951de




###



POST http://localhost:3001/DiscGophers
Content-Type: application/json

{
    "name": "James",
    "password": "Password"
}



###

DELETE http://localhost:3001/DiscGophers/633df10aa244f0f6b1e5a36a



###
PATCH  http://localhost:3001/DiscGophers/633df4a5704d9210286b281a
Content-Type: application/json

{
    "name" : "Ryan"
}